trigger:
- master

pr:
- master

jobs:
- job: windows_debug
  pool:
    name: Hosted
    demands: Cmd
  steps:
  - task: BatchScript@1
    displayName: 'Run scripts/cibuild.cmd'
    inputs:
      filename: scripts/cibuild.cmd
      arguments: '-configuration Debug'

- job: windows_release
  pool:
    name: Hosted
    demands: Cmd
  steps:
  - task: BatchScript@1
    displayName: 'Run scripts/cibuild.cmd'
    inputs:
      filename: scripts/cibuild.cmd
      arguments: '-configuration Release'

- job: ubuntu_1604_debug
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - task: Bash@3
    displayName: 'Run scripts/cibuild.sh'
    inputs:
      filename: scripts/cibuild.sh
      arguments: '--configuration Debug'

- job: ubuntu_1604_release
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - task: Bash@3
    displayName: 'Run scripts/cibuild.sh'
    inputs:
      filename: scripts/cibuild.sh
      arguments: '--configuration Release'
